content:
  - name: sonderzeiten
    label: "Außergewöhnliche Öffnungszeiten"
    type: collection
    path: "sonderzeiten_daten"
    format: json
    extension: json
    fields:
      - name: datum
        label: "Datum"
        type: string
      - name: status
        label: "Status"
        type: string
      - name: grund
        label: "Grund"
        type: string